const { test } = require("node:test");
const assert = require("node:assert/strict");
const ganache = require("ganache");
const { BrowserProvider, ContractFactory, id, ZeroHash } = require("ethers");
const { compile } = require("../scripts/chain-compile");

test("contract independently enforces authorization, schedule, credentials, and exact totals", async t => {
  const ledger = ganache.provider({ logging: { quiet: true }, chain: { hardfork: "shanghai" } });
  const provider = new BrowserProvider(ledger, undefined, { cacheTimeout: -1 });
  t.after(async () => { provider.destroy(); await ledger.disconnect(); });
  const signer = await provider.getSigner(0);
  const outsider = await provider.getSigner(1);
  const artifact = compile();
  const contract = await new ContractFactory(artifact.abi, artifact.bytecode, signer).deploy(await signer.getAddress(), id("test-instance"));
  await contract.waitForDeployment();
  const now = (await provider.getBlock("latest")).timestamp;
  const election = id("election"), first = id("first"), second = id("second"), credential = id("one-voter");
  await assert.rejects(contract.connect(outsider).createElection(election, now, now + 100, [first]));
  await assert.rejects(contract.createElection(election, now, now, [first]));
  await assert.rejects(contract.createElection(election, now, now + 100, []));
  await assert.rejects(contract.createElection(election, now, now + 100, [first, first]));
  await (await contract.createElection(election, now, now + 100, [first, second])).wait();
  await assert.rejects(contract.createElection(election, now, now + 100, [first]));
  await assert.rejects(contract.results(election));
  await assert.rejects(contract.connect(outsider).castVote(election, first, credential, now + 90));
  await assert.rejects(contract.castVote(election, id("invalid"), credential, now + 90));
  await assert.rejects(contract.castVote(election, first, ZeroHash, now + 90));
  await assert.rejects(contract.castVote(election, first, credential, now));
  await assert.rejects(contract.castVote(election, first, credential, now + 101));
  const receipt = await (await contract.castVote(election, first, credential, now + 90)).wait();
  assert.equal(receipt.status, 1);
  assert.equal(await contract.hasVoted(election, credential), true);
  await assert.rejects(contract.castVote(election, second, credential, now + 90));
  await (await contract.createElection(id("future"), now + 50, now + 100, [first])).wait();
  await assert.rejects(contract.castVote(id("future"), first, id("fresh"), now + 90));
  await provider.send("evm_increaseTime", [101]);
  await provider.send("evm_mine", []);
  await assert.rejects(contract.castVote(election, first, id("fresh"), now + 100));
  const [candidates, totals] = await contract.results(election);
  assert.deepEqual([...candidates], [first, second]);
  assert.deepEqual([...totals], [1n, 0n]);
  assert.equal((await contract.queryFilter(contract.filters.BallotAccepted(election))).length, 1);
});
