CREATE TABLE IF NOT EXISTS registered_parties (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  short_name VARCHAR(16) NOT NULL,
  symbol VARCHAR(60) NOT NULL,
  symbol_image MEDIUMBLOB NOT NULL,
  manifesto TEXT NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_ci;
